### ISSUE TITLE
Allow specifying custom module loaders via kabafile.js

### ISSUE THREAD

**Issue by cH40z-Lord** [Becklyn/kaba#15]
Right now we allow customization of various aspects of the Webpack config via `kabafile.js` objects passed to the various Shelf-tasks. This feature, however, lacks support for overriding/specifying module loaders, such as [`riot-tag-loader`](https://github.com/riot/tag-loader).

**Comment by apfelbox** [comment]
Fixed via 6c4f1bd0e74c13c33e5455201b6ab288135b9b4d
