### ISSUE TITLE
Improving webpack performance

### ISSUE THREAD

**Issue by keichinger** [Becklyn/kaba#29]
The following article mentions a bunch of pitfalls that the Outlook team has run into to improve their performance. Maybe we can adopt some of these hints to improve the overall performance of kaba as well:

https://medium.com/@kenneth_chau/speeding-up-webpack-typescript-incremental-builds-by-7x-3912ba4c1d15

**Comment by apfelbox** [comment]
I implemented the TypeScript suggestions with the fork checker and it only saved around 10%, while making the build more complicated and we lose the ability to fail the build directly in case of an error.

So should be fine for now.
